name: route_gpt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+2
  google_generative_ai: ^0.2.0
  location: ^5.0.3
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1
  http: ^1.1.0
  dio: ^5.8.0+1
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  google_fonts: ^6.3.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  loading_animation_widget: ^1.3.0
  lottie: ^3.3.1
  device_info_plus: ^9.1.2
  crypto: ^3.0.3
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/svgs/
    - assets/lottie/

