name: route_gpt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^3.0.0
  stacked_services: ^0.9.0
  get_it: ^7.6.0
  http: ^1.1.0
  google_generative_ai: ^0.2.3
  location: ^6.0.0
  flutter_dotenv: ^5.1.0
  gap: ^3.0.1
  google_fonts: ^6.3.0
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.4
  loading_animation_widget: ^1.3.0
  lottie: ^3.1.3
  device_info_plus: ^9.1.2
  crypto: ^3.0.3
  intl: ^0.18.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: 5.4.4
  golden_toolkit: ^0.15.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/svgs/
    - assets/lottie/

